# Generated by Django 3.0.3 on 2020-02-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20200221_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='beds',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
