# Generated by Django 3.0.3 on 2020-02-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='premium',
        ),
        migrations.AddField(
            model_name='room',
            name='handicap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='quality',
            field=models.CharField(default='vanlig', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='roomnr',
            field=models.PositiveIntegerField(default=404),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='view',
            field=models.BooleanField(default=False),
        ),
    ]
