# Generated by Django 3.0.3 on 2020-02-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
