# Generated by Django 3.0.3 on 2020-03-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_delete_booking'),
        ('rooms', '0005_auto_20200227_1420'),
    ]

    operations = [
    ]
