# Generated by Django 3.0.3 on 2020-03-23 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_merge_20200301_1456'),
        ('rooms', '0006_merge_20200301_1623'),
    ]

    operations = [
    ]
