# Generated by Django 3.0.3 on 2020-03-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_merge_20200323_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='handicap',
            new_name='balcony',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='view',
            new_name='breakfast',
        ),
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='room',
            name='size',
            field=models.PositiveIntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomnr',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
