# Generated by Django 3.0.3 on 2020-03-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20200324_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='minibar',
            field=models.BooleanField(default=False),
        ),
    ]
