export const GET_ROOMS = "GET_ROOMS";
export const SET_CURRENT_ROOM = "SET_CURRENT_ROOM";
export const ADD_BOOKING = "ADD_BOOKING";
export const SET_SELECTED_FROM_DATE = "SET_SELECTED_FROM_DATE";
export const SET_SELECTED_TO_DATE = "SET_SELECTED_TO_DATE";

export const GET_MESSAGES = "GET_MESSAGES";
export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const CREATE_MESSAGE = "CREATE_MESSAGE";
