# Generated by Django 3.0.3 on 2020-02-28 13:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='fromDate',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 2, 28, 13, 45, 14, 292886, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 2, 28, 13, 45, 35, 685786, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='toDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 2, 28, 13, 45, 49, 788199, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
