# Generated by Django 3.0.3 on 2020-03-24 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20200324_1524'),
        ('bookings', '0002_auto_20200228_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='roomnr',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='rooms.Room', to_field='roomnr'),
            preserve_default=False,
        ),
    ]
